### ISSUE TITLE
Recent change breaks systems with exceptions disabled

### ISSUE THREAD

**Issue by cdotstout** [KhronosGroup/Vulkan-Hpp#113] opened 2017-06-21 21:42 UTC
Using clang, with exceptions disabled, client code is hitting several error messages such as:

../../third_party/vulkan_loader_and_validation_layers/include/vulkan/vulkan.hpp:747:41: error: cannot use 'throw' with exceptions disabled
    case Result::eErrorOutOfHostMemory: throw OutOfHostMemoryError ( message );

This change seems to have introduced the problem:

commit 6e9d9b51114e46c5616c8cc97a20b04720e22e58
Author: Damian Dyńdo <ripper37@gmail.com>
Date:   Wed Apr 26 09:30:24 2017 +0200

    Introduce custom exceptions for Vulkan-Hpp (#97) (#99)

**Comment by schwa423** [comment] 2017-08-08 19:40
Looks like this is fixed in 1.0.55, just need to wait for the SDK to arrive.

**Comment by mtavenrath** [comment] 2017-09-29 08:07
@cdotstout Can you confirm that the issue is fixed?

**Comment by mtavenrath** [comment] 2017-11-30 12:39
Fixed with 1.0.55. Closing.

**Closed by mtavenrath** 2017-11-30 12:39 UTC
