### ISSUE TITLE
Multiple definition error with isStructureChainValid

### ISSUE THREAD

**Issue by lmagder** [KhronosGroup/Vulkan-Hpp#128] opened 2017-09-16 04:53 UTC
Starting with the VulkanSDK 1.0.61.0 programs with more than one file including vulkan.hpp no longer compile with VS2017

The `isStructureChainValid` functions are not declared `inline` so the linker does not allow multiple definitions.

`error LNK2005: "bool __cdecl vk::isStructureChainValid<struct vk::PresentInfoKHR,struct vk::DisplayPresentInfoKHR>(void)" (??$isStructureChainValid@UPresentInfoKHR@vk@@UDisplayPresentInfoKHR@2@@vk@@YA_NXZ) already defined in Cameras.cpp.obj`

I'm assuming this must be MSVC-specific since other people are using this code, but I didn't test. 😃

**Comment by lmagder** [comment] 2017-09-16 05:19
Actually it looks like you guys already fixed this by adding `constexpr`, but unfortunately the SDK released a few days ago is still broken, not sure if I should leave this open or open another issue elsewhere.

**Comment by Markyparky56** [comment] 2017-09-16 17:11
Running into the same issue, and a quick find & replace for all the `template<> bool isStructureChainValid` to include constexpr it now compiles. 

A bit confused regarding versions however, the one in the Vulkan-Hpp vulkan folder (from this repo) still requires VK_HEADER_VERSION 57. The file here however is larger than the one in the LunarG 1.0.57.0 SDK (1,229KB vs 1,182KB respectively). 
Attempting to generate a new vulkan.hpp file with the Vulkan-Docs submodule set to the [latest commit from yesterday](https://github.com/KhronosGroup/Vulkan-Docs/commit/0cc6bba634aeecb88e4b43f1bdfd84a339c1869e) however doesn't work as it throws an exception/assert on line 1690, something to do with readExtensionsExtension and a null child. Granted I've never tried to generate my own copy before so forgive my naivete (works with this [commit](https://github.com/KhronosGroup/Vulkan-Docs/commit/a9231ec465ec08eb367fc990ca160fe45d545470) though). This still leaves the question of where LunarG is getting their version of vulkan.hpp from, both the one shipped with 57 and the one in the 61 SDK? It's also interesting to note that the latest SDK was released before the Vulkan-Docs repo was updated with the new spec.

**Comment by asuessenbach** [comment] 2017-09-18 12:43
> This still leaves the question of where LunarG is getting their version of vulkan.hpp from, both the one shipped with 57 and the one in the 61 SDK?
Indeed, that seems to be a valid question to the LunarG guys!

**Comment by afrantzis** [comment] 2017-09-20 08:32
@lmagder I suggest opening a bug in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues (or I can do it if you prefer)

**Comment by mikes-lunarg** [comment] 2017-09-20 15:21
LunarG is tracking this as an SDK issue here: https://vulkan.lunarg.com/issue/view/59becf9f663151467fab653d

We will be rolling a 1.0.61.1 SDK shortly to address this issue

**Comment by mtavenrath** [comment] 2017-09-29 07:59
The issue is fixed in the generater and I've submitted an updated version of the header for Vulkan 1.0.61.

**Closed by mtavenrath** 2017-09-29 07:59 UTC
