### ISSUE TITLE
[Bug] ld.lld: error: undefined symbol: _glfwInitJoysticksLinux

### ISSUE THREAD

**Issue by AmericaPacific42** [KhronosGroup/Vulkan-Hpp#1676] opened 2023-10-06 17:07 UTC
`~/Vulkan-Hpp $ cmake --build .
[  0%] Building CXX object CMakeFiles/VulkanHppGenerator.dir/VulkanHppGenerator.cpp.o
^Cmake[2]: *** [CMakeFiles/VulkanHppGenerator.dir/build.make:76: CMakeFiles/VulkanHppGenerator.dir/VulkanHppGenerator.cpp.o] Interrupt
make[1]: *** [CMakeFiles/Makefile2:2606: CMakeFiles/VulkanHppGenerator.dir/all] Interrupt
make: *** [Makefile:136: all] Interrupt

~/Vulkan-Hpp $ cmake --build . --clean-first
[  0%] Building CXX object CMakeFiles/VulkanHppGenerator.dir/VulkanHppGenerator.cpp.o
c![  1%] Building CXX object CMakeFiles/VulkanHppGenerator.dir/tinyxml2/tinyxml2.cpp.o
[  1%] Linking CXX executable VulkanHppGenerator
[  1%] Built target VulkanHppGenerator
[  1%] Building CXX object CMakeFiles/VideoHppGenerator.dir/VideoHppGenerator.cpp.o
[  2%] Building CXX object CMakeFiles/VideoHppGenerator.dir/tinyxml2/tinyxml2.cpp.o
[  2%] Linking CXX executable VideoHppGenerator
[  2%] Built target VideoHppGenerator
[  2%] Building C object glfw/src/CMakeFiles/glfw.dir/context.c.o
[  3%] Building C object glfw/src/CMakeFiles/glfw.dir/init.c.o
[  3%] Building C object glfw/src/CMakeFiles/glfw.dir/input.c.o
[  3%] Building C object glfw/src/CMakeFiles/glfw.dir/monitor.c.o
[  4%] Building C object glfw/src/CMakeFiles/glfw.dir/vulkan.c.o
[  4%] Building C object glfw/src/CMakeFiles/glfw.dir/window.c.o
[  4%] Building C object glfw/src/CMakeFiles/glfw.dir/x11_init.c.o
[  4%] Building C object glfw/src/CMakeFiles/glfw.dir/x11_monitor.c.o
[  5%] Building C object glfw/src/CMakeFiles/glfw.dir/x11_window.c.o
[  5%] Building C object glfw/src/CMakeFiles/glfw.dir/xkb_unicode.c.o
[  5%] Building C object glfw/src/CMakeFiles/glfw.dir/posix_time.c.o
[  6%] Building C object glfw/src/CMakeFiles/glfw.dir/posix_thread.c.o
[  6%] Building C object glfw/src/CMakeFiles/glfw.dir/glx_context.c.o
[  6%] Building C object glfw/src/CMakeFiles/glfw.dir/egl_context.c.o
[  7%] Building C object glfw/src/CMakeFiles/glfw.dir/osmesa_context.c.o
[  7%] Building C object glfw/src/CMakeFiles/glfw.dir/null_joystick.c.o
[  7%] Linking C static library libglfw3.a
[  7%] Built target glfw
[  7%] Generating HTML documentation
warning: Tag 'TCL_SUBST' at line 216 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'COLS_IN_ALPHA_INDEX' at line 877 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'HTML_TIMESTAMP' at line 983 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'FORMULA_TRANSPARENT' at line 1205 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'LATEX_SOURCE_CODE' at line 1391 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLASS_DIAGRAMS' at line 1661 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_FONTNAME' at line 1691 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_FONTSIZE' at line 1696 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_TRANSPARENT' at line 1845 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[  7%] Built target docs
[  7%] Building CXX object glslang/glslang/CMakeFiles/GenericCodeGen.dir/GenericCodeGen/CodeGen.cpp.o
[  8%] Building CXX object glslang/glslang/CMakeFiles/GenericCodeGen.dir/GenericCodeGen/Link.cpp.o
[  8%] Linking CXX static library libGenericCodeGen.a
[  8%] Built target GenericCodeGen
[  8%] Building CXX object glslang/OGLCompilersDLL/CMakeFiles/OGLCompiler.dir/InitializeDll.cpp.o
[  9%] Linking CXX static library libOGLCompiler.a
[  9%] Built target OGLCompiler
[  9%] Building CXX object glslang/glslang/OSDependent/Unix/CMakeFiles/OSDependent.dir/ossource.cpp.o
[  9%] Linking CXX static library libOSDependent.a
[  9%] Built target OSDependent
[  9%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch
[ 10%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/glslang_tab.cpp.o
MachineIndependent/glslang_tab.cpp:4937:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
1 warning generated.
[ 10%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/attribute.cpp.o
[ 10%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/Constant.cpp.o
[ 10%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/iomapper.cpp.o
[ 11%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/InfoSink.cpp.o
[ 11%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/Initialize.cpp.o
[ 11%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/IntermTraverse.cpp.o
[ 12%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/Intermediate.cpp.o
[ 12%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/ParseContextBase.cpp.o
[ 12%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/ParseHelper.cpp.o
[ 13%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/PoolAlloc.cpp.o
[ 13%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/RemoveTree.cpp.o
[ 13%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/Scan.cpp.o
[ 13%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/ShaderLang.cpp.o
[ 14%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/SpirvIntrinsics.cpp.o
[ 14%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/SymbolTable.cpp.o
[ 14%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/Versions.cpp.o
[ 15%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/intermOut.cpp.o
[ 15%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/limits.cpp.o
[ 15%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/linkValidate.cpp.o
[ 15%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/parseConst.cpp.o
[ 16%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/reflection.cpp.o
[ 16%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/preprocessor/Pp.cpp.o
[ 16%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/preprocessor/PpAtom.cpp.o
[ 17%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/preprocessor/PpContext.cpp.o
[ 17%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/preprocessor/PpScanner.cpp.o
[ 17%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/preprocessor/PpTokens.cpp.o
[ 18%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/propagateNoContraction.cpp.o
[ 18%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslAttributes.cpp.o
[ 18%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslParseHelper.cpp.o
[ 18%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslScanContext.cpp.o
[ 19%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslOpMap.cpp.o
[ 19%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslTokenStream.cpp.o
[ 19%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslGrammar.cpp.o
[ 20%] Building CXX object glslang/glslang/CMakeFiles/MachineIndependent.dir/HLSL/hlslParseables.cpp.o
[ 20%] Linking CXX static library libMachineIndependent.a
[ 20%] Built target MachineIndependent
[ 20%] Building CXX object glslang/glslang/CMakeFiles/glslang.dir/CInterface/glslang_c_interface.cpp.o
[ 21%] Linking CXX static library libglslang.a
[ 21%] Built target glslang
[ 21%] Building CXX object glslang/StandAlone/CMakeFiles/glslang-default-resource-limits.dir/ResourceLimits.cpp.o
[ 21%] Building CXX object glslang/StandAlone/CMakeFiles/glslang-default-resource-limits.dir/resource_limits_c.cpp.o
[ 22%] Linking CXX static library libglslang-default-resource-limits.a
[ 22%] Built target glslang-default-resource-limits
[ 23%] Building CXX object glslang/SPIRV/CMakeFiles/SPVRemapper.dir/SPVRemapper.cpp.o
[ 23%] Building CXX object glslang/SPIRV/CMakeFiles/SPVRemapper.dir/doc.cpp.o
[ 23%] Linking CXX static library libSPVRemapper.a
[ 23%] Built target SPVRemapper
[ 24%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o
[ 24%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/InReadableOrder.cpp.o
[ 24%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/Logger.cpp.o
[ 25%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/SpvBuilder.cpp.o
[ 25%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/SpvPostProcess.cpp.o
[ 25%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/doc.cpp.o
[ 25%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/SpvTools.cpp.o
[ 26%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/disassemble.cpp.o
[ 26%] Building CXX object glslang/SPIRV/CMakeFiles/SPIRV.dir/CInterface/spirv_c_interface.cpp.o
[ 26%] Linking CXX static library libSPIRV.a
[ 26%] Built target SPIRV
[ 26%] Generating /data/data/com.termux/files/home/Vulkan-Hpp/include/glslang/glsl_intrinsic_header.h
[ 26%] Building CXX object glslang/StandAlone/CMakeFiles/glslangValidator.dir/StandAlone.cpp.o
[ 26%] Linking CXX executable glslangValidator
[ 26%] Built target glslangValidator
[ 27%] Building CXX object glslang/StandAlone/CMakeFiles/spirv-remap.dir/spirv-remap.cpp.o
[ 27%] Linking CXX executable spirv-remap
[ 27%] Built target spirv-remap
[ 27%] Building CXX object glslang/hlsl/CMakeFiles/HLSL.dir/stub.cpp.o
[ 28%] Linking CXX static library libHLSL.a
[ 28%] Built target HLSL
[ 28%] Building CXX object samples/utils/CMakeFiles/utils.dir/cmake_pch.hxx.pch
[ 29%] Building CXX object samples/utils/CMakeFiles/utils.dir/math.cpp.o
[ 29%] Building CXX object samples/utils/CMakeFiles/utils.dir/shaders.cpp.o
[ 29%] Building CXX object samples/utils/CMakeFiles/utils.dir/utils.cpp.o
[ 30%] Linking CXX static library libutils.a
[ 30%] Built target utils
[ 30%] Building CXX object samples/01_InitInstance/CMakeFiles/01_InitInstance.dir/cmake_pch.hxx.pch
[ 30%] Building CXX object samples/01_InitInstance/CMakeFiles/01_InitInstance.dir/01_InitInstance.cpp.o
[ 30%] Linking CXX executable 01_InitInstance
[ 30%] Built target 01_InitInstance
[ 31%] Building CXX object samples/02_EnumerateDevices/CMakeFiles/02_EnumerateDevices.dir/02_EnumerateDevices.cpp.o
[ 31%] Linking CXX executable 02_EnumerateDevices
ld.lld: error: undefined symbol: _glfwInitJoysticksLinux
>>> referenced by x11_init.c:1238
>>>               x11_init.c.o:(_glfwPlatformInit) in archive ../../glfw/src/libglfw3.a

ld.lld: error: undefined symbol: _glfwTerminateJoysticksLinux
>>> referenced by x11_init.c:1336
>>>               x11_init.c.o:(_glfwPlatformTerminate) in archive ../../glfw/src/libglfw3.a

ld.lld: error: undefined symbol: _glfwDetectJoystickConnectionLinux
>>> referenced by x11_window.c:2786
>>>               x11_window.c.o:(_glfwPlatformPollEvents) in archive ../../glfw/src/libglfw3.a
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [samples/02_EnumerateDevices/CMakeFiles/02_EnumerateDevices.dir/build.make:109: samples/02_EnumerateDevices/02_EnumerateDevices] Error 1
make[1]: *** [CMakeFiles/Makefile2:3839: samples/02_EnumerateDevices/CMakeFiles/02_EnumerateDevices.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

**Comment by romanovj** [comment] 2023-10-06 17:16
not a bug, patches for termux are here https://github.com/termux/termux-packages/tree/master/x11-packages/glfw

**Comment by AmericaPacific42** [comment] 2023-10-06 17:29
`
~/Vulkan-Hpp $ git clone https://github.com/termux/termux-packages/tree/master/x11-packages/glfw.git
Cloning into 'glfw'...
fatal: repository 'https://github.com/termux/termux-packages/tree/master/x11-packages/glfw.git/' not found
~/Vulkan-Hpp $ git clone https://github.com/termux/termux-packages/tree/master/x11-packages/glfw
Cloning into 'glfw'...
fatal: repository 'https://github.com/termux/termux-packages/tree/master/x11-packages/glfw/' not found`

**Comment by AmericaPacific42** [comment] 2023-10-06 17:31
`~/Vulkan-Hpp $ pkg install glfw
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
glfw is already the newest version (3.3.8-p20230303-0).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
~/Vulkan-Hpp $ cmake --build .
[0/1] Re-running CMake...
--  Found clang-format version <16.0.6>.
--  Using .clang-format version 15.
CMake Deprecation Warning at glm/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at glm/CMakeLists.txt:2 (cmake_policy):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at CMakeLists.txt:421 (add_subdirectory):
  add_subdirectory given source "glfw" which is not an existing directory.


CMake Deprecation Warning at glslang/CMakeLists.txt:36 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  glslang/CMakeLists.txt:315 (find_host_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  glslang/StandAlone/CMakeLists.txt:34 (find_host_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
FAILED: build.ninja
/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S/data/data/com.termux/files/home/Vulkan-Hpp -B/data/data/com.termux/files/home/Vulkan-Hpp
ninja: error: rebuilding 'build.ninja': subcommand failed
~/Vulkan-Hpp $ pkg install glfw
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
glfw is already the newest version (3.3.8-p20230303-0).`

**Comment by theHamsta** [comment] 2023-10-09 12:33
You seem to run a very special environment (Android)? Could you provide us a Dockerfile so we could reproduce your environment? Preferably `ubuntu:22.04` if this is a general Linux issue. Your issue seems to be related to your build environment not Vulkan-Hpp.

**Comment by asuessenbach** [comment] 2023-10-16 08:02
Closing this out. If you think, this is still an issue, please re-open.

**Closed by asuessenbach** 2023-10-16 08:02 UTC

**Comment by AmericaPacific42** [comment] 2023-10-16 16:14
Still broken in latest version
