### ISSUE TITLE
can't generate vulkan.hpp with latest (from git) vk.xml

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/Vulkan-Hpp#139] opened 2017-10-21 13:58 UTC
with the latest vk.xml from git

```
Loading vk.xml from /tmp/makepkg/vulkan-git/src/Vulkan-Docs/src/spec/vk.xml
Writing vulkan.hpp to /tmp/makepkg/vulkan-git/src/Vulkan-Hpp/vulkan/vulkan.hpp
caught exception: basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 3)
```

**Comment by mtavenrath** [comment] 2017-10-24 14:36
The issue is fixed with the last commit which bumps the header to 1.0.64.

**Closed** 2017-10-24 14:36 UTC
