### ISSUE TITLE
Flags<BitType> operator~ does not compile

### ISSUE THREAD

**Issue by Stef-2** [KhronosGroup/Vulkan-Hpp#1501] opened 2023-02-09 10:48 UTC
Recently I included Vulkan Memory Allocator C++ bindings to my project which uses some of these flag bitwise operators, and the project no longer compiles since ``Flags<BitType> operator~`` doesn't seem to be working:

```C++
VULKAN_HPP_CONSTEXPR Flags<BitType> operator~() const VULKAN_HPP_NOEXCEPT
    {
      return Flags<BitType>( m_mask ^ FlagTraits<BitType>::allFlags.m_mask );
    }
```
the solution seems to be to remove ``.m_mask``:
```C++
return Flags<BitType>(m_mask ^ FlagTraits<BitType>);
```
Searching through previously closed issues, it looks like this was introduced in issue #1437

**Comment by asuessenbach** [comment] 2023-02-09 12:15
I would be very surprised if `return Flags<BitType>(m_mask ^ FlagTraits<BitType>);` would work, as `FlagTraits<BitType>` is a type and not an expression.
What compiler errors do you get?

**Comment by Stef-2** [comment] 2023-02-09 22:08
My mistake, changing the return into ``return Flags<BitType>(m_mask ^ FlagTraits<BitType>::allFlags);`` "fixed" it for me,
 not ``return Flags<BitType>(m_mask ^ FlagTraits<BitType>);`` as I wrote in the original post.

Attempting to compile with the unmodified ``vulkan.hpp`` using the latest MSVC compiler produces the following error:
``C2228	left of '.m_mask' must have class/struct/union``

**Comment by asuessenbach** [comment] 2023-02-13 12:40
I've added a Flags test project with #1502.
Could you please verify that it compiles without errors on your end?
If it doesn't cover your issue, would you mind to extend it accordingly?

**Comment by asuessenbach** [comment] 2023-03-13 08:10
Closing this out for now. Please reopen if it's still valid.

**Comment by Latias94** [comment] 2023-03-18 06:45
I can reproduce when I use Vulkan-Hpp with https://github.com/YaaZ/VulkanMemoryAllocator-Hpp.
The error produce in my project is
```shell
F:\SDKs\VulkanSDK\1.3.239.0\include\vulkan/vulkan.hpp(457): error C2228: left of '.m_mask' must have class/struct/union
F:\SDKs\VulkanSDK\1.3.239.0\include\vulkan/vulkan.hpp(457): note: type is 'vk::FlagTraits<vma::VirtualAllocationCreateFlagBits>::<unnamed-enum-allFlags>'
F:\SDKs\VulkanSDK\1.3.239.0\include\vulkan/vulkan.hpp(456): note: while compiling class template member function 'vk::Flags<vma::VirtualAllocationCreateFlagBits> vk::Flags<vma::VirtualAllocationCreateFlagBits>::operator ~(void) noexcept const'
C:\Users\Frankorz\AppData\Local\.xmake\packages\v\vulkan-memory-allocator-hpp\v3.0.1\b1820fc4ee8d40c39f17f06e76174713\include\vk_mem_alloc_enums.hpp(442): note: see reference to function template instantiation 'vk::Flags<vma::VirtualAllocationCreateFlagBits> vk::Flags<vma::VirtualAllocationCreateFlagBits>::operator ~(void) noexcept const' being compiled
C:\Users\Frankorz\AppData\Local\.xmake\packages\v\vulkan-memory-allocator-hpp\v3.0.1\b1820fc4ee8d40c39f17f06e76174713\include\vk_mem_alloc_enums.hpp(429): note: see reference to class template instantiation 'vk::Flags<vma::VirtualAllocationCreateFlagBits>' being compiled
```
https://github.com/YaaZ/VulkanMemoryAllocator-Hpp/blob/2e9ab714e9f0cdf6d07891fa6f359e91f3096369/include/vk_mem_alloc_enums.hpp#L436

I add related code in your test project

```cpp

#include <vulkan/vulkan.hpp>

namespace vk {

enum class VirtualAllocationCreateFlagBits : uint32_t {
  eUpperAddress = 0x00000040,
  eStrategyMinMemory = 0x00010000,
  eStrategyMinTime = 0x00020000,
  eStrategyMinOffset = 0x00040000
};

template <> struct FlagTraits<VirtualAllocationCreateFlagBits> {
  enum : uint32_t {
    allFlags = uint32_t(VirtualAllocationCreateFlagBits::eUpperAddress) |
               uint32_t(VirtualAllocationCreateFlagBits::eStrategyMinMemory) |
               uint32_t(VirtualAllocationCreateFlagBits::eStrategyMinTime) |
               uint32_t(VirtualAllocationCreateFlagBits::eStrategyMinOffset)
  };
};
using VirtualAllocationCreateFlags = vk::Flags<VirtualAllocationCreateFlagBits>;
} // namespace vk

int main(int /*argc*/, char ** /*argv*/) {
  vk::MemoryHeapFlags mhf0;
  assert(mhf0.m_mask == 0);

  vk::MemoryHeapFlags mhf1(vk::MemoryHeapFlagBits::eDeviceLocal);
  assert(mhf1.m_mask == VK_MEMORY_HEAP_DEVICE_LOCAL_BIT);

  vk::MemoryHeapFlags mhf2(mhf1);
  assert(mhf2.m_mask == VK_MEMORY_HEAP_DEVICE_LOCAL_BIT);

  VkMemoryHeapFlags vkmhf =
      VK_MEMORY_HEAP_DEVICE_LOCAL_BIT | VK_MEMORY_HEAP_MULTI_INSTANCE_BIT;
  vk::MemoryHeapFlags mhf3(vkmhf);
  assert(mhf3.m_mask ==
         (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT | VK_MEMORY_HEAP_MULTI_INSTANCE_BIT));

  // error
  // vk::MemoryHeapFlags mhf4( vk::MemoryHeapFlagBits::eDeviceLocal |
  // vk::ImageAspectFlagBits::eDepth );

  assert(mhf0 < mhf1);
  assert(!(mhf1 < mhf2));

  assert(mhf0 <= mhf1);
  assert(mhf1 <= mhf2);
  assert(!(mhf3 <= mhf2));

  assert(mhf1 > mhf0);
  assert(!(mhf2 > mhf1));

  assert(mhf1 >= mhf0);
  assert(mhf2 >= mhf1);
  assert(!(mhf2 >= mhf3));

  assert(!(mhf0 == mhf1));
  assert(mhf1 == mhf2);

  assert(mhf0 != mhf1);
  assert(!(mhf1 != mhf2));

  assert(!mhf0);
  assert(!!mhf1);

  assert(mhf1 & vk::MemoryHeapFlagBits::eDeviceLocal);
  assert(!(mhf0 & vk::MemoryHeapFlagBits::eDeviceLocal));

  assert((mhf0 | vk::MemoryHeapFlagBits::eDeviceLocal) ==
         vk::MemoryHeapFlagBits::eDeviceLocal);
  assert((mhf1 | vk::MemoryHeapFlagBits::eDeviceLocal) ==
         vk::MemoryHeapFlagBits::eDeviceLocal);

  assert((mhf0 ^ mhf1) == mhf1);
  assert((mhf1 ^ mhf2) == mhf0);

  vk::MemoryHeapFlags mhf4(~mhf0);
  assert(mhf4 == (vk::MemoryHeapFlagBits::eDeviceLocal |
                  vk::MemoryHeapFlagBits::eMultiInstance));

  mhf0 = mhf1;
  assert(mhf0 == mhf1);

  mhf0 |= vk::MemoryHeapFlagBits::eMultiInstance;
  assert(mhf0 & vk::MemoryHeapFlagBits::eMultiInstance);

  mhf0 &= vk::MemoryHeapFlagBits::eDeviceLocal;
  assert(mhf0 & vk::MemoryHeapFlagBits::eDeviceLocal);

  mhf0 ^= mhf3;
  assert(mhf0 == (vk::MemoryHeapFlagBits::eMultiInstance));

  assert(mhf0);

  vkmhf = static_cast<VkMemoryHeapFlags>(mhf0);

  auto flags { ~(vk::VirtualAllocationCreateFlags(vk::VirtualAllocationCreateFlagBits::eUpperAddress))};

  return 0;
}

```

and failed with:

```shell
❯ xmake -rvD
[ 25%]: cache compiling.release src\main.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast /EHsc -external:W0 -external:IF:\SDKs\VulkanSDK\1.3.239.0\include -external:W0 -external:IC:\Users\Frankorz\AppData\Local\.xmake\packages\v\vulkan-hpp\v1.3.231\25d2b8b809c24dd993e401b77f3dc7c4\include -DNDEBUG -Fobuild\.objs\test_flags\windows\x64\release\src\main.cpp.obj src\main.cpp
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\modules\private\action\build\object.lua:91: @programdir\modules\core\tools\cl.lua:648: main.cpp
F:\SDKs\VulkanSDK\1.3.239.0\include\vulkan/vulkan.hpp(457): error C2228: left of '.m_mask' must have class/struct/union
F:\SDKs\VulkanSDK\1.3.239.0\include\vulkan/vulkan.hpp(457): note: type is 'vk::FlagTraits<vk::VirtualAllocationCreateFlagBits>::<unnamed-enum-allFlags>'
F:\SDKs\VulkanSDK\1.3.239.0\include\vulkan/vulkan.hpp(456): note: while compiling class template member function 'vk::Flags<vk::VirtualAllocationCreateFlagBits> vk::Flags<vk::VirtualAllocationCreateFlagBits>::operator ~(void) noexcept const'
src\main.cpp(126): note: see reference to function template instantiation 'vk::Flags<vk::VirtualAllocationCreateFlagBits> vk::Flags<vk::VirtualAllocationCreateFlagBits>::operator ~(void) noexcept const' being compiled
src\main.cpp(126): note: see reference to class template instantiation 'vk::Flags<vk::VirtualAllocationCreateFlagBits>' being compiled
```

**Comment by asuessenbach** [comment] 2023-03-20 08:51
The problem is not in Vulkan-Hpp, but in your `VirtualAllocationCreateFlag[Bit]s`.
If I modify it slightly, to be closer to how it's done in Vulkan-Hpp, everything compiles fine on my end:
```
namespace vk
{
  enum class VirtualAllocationCreateFlagBits : uint32_t
  {
    eUpperAddress      = 0x00000040,
    eStrategyMinMemory = 0x00010000,
    eStrategyMinTime   = 0x00020000,
    eStrategyMinOffset = 0x00040000
  };

  using VirtualAllocationCreateFlags = vk::Flags<VirtualAllocationCreateFlagBits>;

  template <>
  struct FlagTraits<VirtualAllocationCreateFlagBits>
  {
    static constexpr bool                         isBitmask = true;
    static constexpr VirtualAllocationCreateFlags allFlags =
      VirtualAllocationCreateFlagBits::eUpperAddress | VirtualAllocationCreateFlagBits::eStrategyMinMemory | VirtualAllocationCreateFlagBits::eStrategyMinTime |
      VirtualAllocationCreateFlagBits::eStrategyMinOffset;
  };
}  // namespace vk

```

**Comment by Latias94** [comment] 2023-03-20 09:17
ok, I found that vma-hpp has fix these issues but not include in its new release yet. 
Sorry, I think my issue has been resolved.

**Closed** 2023-03-20 09:25 UTC
