### ISSUE TITLE
Expose Vulkan defines as (constexpr?) variables

### ISSUE THREAD

**Issue by RippeR37** [KhronosGroup/Vulkan-Hpp#107] opened 2017-05-18 11:35 UTC
I find it very distrubing that we are forced to mix C-style code with C++, as `vulkan.h` defines many "objects" with `#define`. With Vulkan-HPP we can do better - maybe we could simply expose some of these objects as constexpr (when supported) variables/objects? This would purify our code from C-like macros and defines.

Note that Vulkan-HPP already depends on specific version of `vulkan.h` so there shouldn't be any compatibility reason to not provide such feature.

Some example variables/objects that we use commonly:
* `VK_NULL_HANDLE`
* `VK_TRUE` / `VK_FALSE`
* etc.

**Comment by mtavenrath** [comment] 2017-05-18 14:55
@RippeR37 In which cases do you need VK_NULL_HANDLE? All Vulkan C++ initialize to VK_NULL_HANDLE by default. Due to this you can use either vk::Image or {} instead of VK_NULL_HANDLE. For VK_TRUE / VK_FALSE it also should be possible to replace them by true/false.

Which 'objects' are causing annoyance besides those two?

**Comment by RippeR37** [comment] 2017-05-18 15:35
@mtavenrath
- as for `VK_NULL_HANDLE` I believe there might be some structures where you have to pass handle to some object or mentioned `VK_NULL_HANDLE` (per use-case) so while functions and methods have often C++-related enhancements, I'm not sure if there are no places in Vulkan where you'd still have to provide simple `VK_NULL_HANDLE`
- as for `VkBool`, `VK_TRUE / VK_FALSE` and `true / false` - while true, that with current mapping (and probably this will stay this way to avoid big confusion) one could pass simply `true` or `false` and it should work nicely, though when one pass something as `VkBool` and not `bool`, it might look "cleaner" to him to user proper values there. I'm not 100% advising here for that, but if you'd decide to expose some defined constants/variables/objects it might be good to expose these as well.

As for other objects, its hard to just sift through whole `vulkan.h` to list them, but here are some that comes to mind (for those who prefer not to use C preprocessor unless necessary):
- `VK_VERSION_1_0` (and any future versions too)
- `VK_MAKE_VERSION()` macro
- `VK_API_VERSION_1_0`
- `VK_VERSION_*()`
- `VK_NULL_HANDLE`
- `VK_LOD_CLAMP_NONE`
- `VK_REMAINING_MIP_LEVELS`
- `VK_WHOLE_SIZE`
- `VK_ATTACHMENT_UNUSED`
- `VK_TRUE / VK_FALSE`
- `VK_QUEUE_FAMILY_IGNORED`
- `VK_SUBPASS_EXTERNAL`
- `VK_MAX_PHYSICAL_DEVICE_NAME_SIZE`
- `VK_UUID_SIZE`
- `VK_MAX_MEMORY_TYPES`
- `VK_MAX_MEMORY_HEAPS`
- `VK_MAX_EXTENSION_NAME_SIZE`
- `VK_MAX_DESCRIPTION_SIZE`

And this is only some part taken directly from current `vulkan.h` at KhronosGroup/Vulkan-Docs. I understand that some of these might not be used too often, but it shouldn't be a problem to define such `constexpr` constants/variables/functions/objects/etc. for those who use them. C++ provides better alternative that these old-school defines, so why not use them and have consistent naming with rest of the C++ wrapper?

Also there are many special values that represents specific behavior. Though it's not special value per-se, one might also consider `UINT64_MAX` to be "special" as we often use it as "wait forever" for fence and this is pretty much usual usage, so it's not like only couple people would benefit from this. Exposing such special values might make code clearer and easier to understand and might be better then making everyone make their own definitions each time (just consider pi from standard library ...). Maybe this one is not the best example, but it's used very often and passing some macro-value is definitely less-readable then something like `vk::WaitForever` or `vk::MaxWaitTime` or something like that.

**Comment by ioquatix** [comment] 2017-07-29 05:31
> Also there are many special values that represents specific behavior. Though it's not special value per-se, one might also consider UINT64_MAX to be "special" as we often use it as "wait forever" for fence a

I'm honesty surprised anyone would do this as I personally prefer to put it in a loop.

**Comment by mtavenrath** [comment] 2017-11-30 10:13
Closing as duplicate of #138.

**Closed by mtavenrath** 2017-11-30 10:13 UTC
