### ISSUE TITLE
throwResultException terminates program in some drivers

### ISSUE THREAD

**Issue by ericberdahl** [KhronosGroup/Vulkan-Hpp#147] opened 2017-11-22 20:04 UTC
vk::throwResultException currently asserts that the Result argument is negative. This is the clear intention of the Vulkan specification, but is violated by conforming drivers in the field (at least one on a relatively popular platform). In such a driver, a positive result code is returned as a failure code from the driver.

When vulkan.hpp is used to code programs run against such a driver, a regular API failure is thereby promoted to a premature application termination.

There are several possible solutions to this issue. The easiest may be to remove the assertion altogether, or at least reduce the scope of the assertion to asserting the the Result is not eSuccess.

**Comment by mtavenrath** [comment] 2017-11-24 10:28
@ericberdahl I'd be open to add a define to change the behavior of the assertion to one of your solutions for people working with drivers which violate the intention of the Vulkan specification. Nevertheless I'd like to figure out why the intention of the spec is being violated and try to get the root cause of this issue fixed. Can you give me more information about the exact issue you're seeing?

**Comment by ericberdahl** [comment] 2017-11-27 20:09
@mtavenrath I'm most on the same page with you with respect to understanding how the world got into the space it is today, while simultaneously recognizing that we are where we are and working to find a usable solution. That's a relatively formal way of saying thanks for engaging in the conversation.

The driver and platform in question is a widely popular set, in the hands of millions of users worldwide -- I am being intentionally circumspect about naming the specific parties in a public forum, mostly out of decorum. The place I most often see this specific issue is from vkCreateComputePipelines, where a non-negative result code is returned (most common culprit is VK_INCOMPLETE). The root cause, both of the non VK_SUCCESS return and underlying issue, is an acknowledged driver bug. However, that does not mitigate against the fact that drivers in the wild are yet returning positive result codes as errors in these cases. I am irked by the situation, but cannot change it.

It also worth noting that the language in the Vulkan spec which describes the intent of the working group to indicate errors only with negative return values and success with non-negative return values is, at best, illustrative, and cannot be successfully tested. That is, one can't write a conformance test against that assertion and applications ought to code defensively against a conforming driver that nonetheless violates this proscription.

Instead of encoding the test as an assert, throwResultException may wish to perform a test (perhaps debug mode) and emit a diagnostic warning of some kind. Ultimately, it is the driver that is non-conforming, and having the application prematurely terminate because of a non-fatal bug in the driver seems like a heavy price for the application to pay.

**Comment by mtavenrath** [comment] 2017-11-30 14:13
We decided to remove the assertion. In fact it's completely legit to throw an exception in all cases where the driver returns a result which is not listed in the successful return codes list at the time of compilation of the program. If the spec introduces new success codes for a function they will most likely require special handling, so it'd good to throw them because the application would most likely crash afterwards anyways.

**Comment by mtavenrath** [comment] 2017-11-30 14:33
Fix has been merged. Closing.

**Closed by mtavenrath** 2017-11-30 14:33 UTC
