### ISSUE TITLE
Plans for an OpenGL-Hpp?

### ISSUE THREAD

**Issue by alaingalvan** [KhronosGroup/Vulkan-Hpp#48] opened 2016-11-17 17:01 UTC
I love how **Vulkan-Hpp** offers OOP patterns and compile time type checking for Vulkan constructs, and I'm wondering if there's any plans to bring that same style of header only library to OpenGL as an officially maintained library.

I know there's challenges involved like deciding what extension bindings to include for OpenGL, how far to take the abstraction, and there's a number of libraries like [glad](https://github.com/Dav1dde/glad) and [OOGL](https://github.com/Overv/OOGL) that try solving this, but they either still opt for doing things in a C style or they don't pull from the specification to generate the library.

Here's a rough idea on how I would imagine it would look:

```cpp
auto program = gl::Program();

auto vert = gl::Shader(gl::ShaderType::eVertex);
vert.source("#version 150\nin vec2 position; void main() { gl_Position = vec4(position, 0.0, 1.0); }");
vert.compile(); // Like Vulkan-Hpp, this would throw an exception if there was an error.

auto frag = gl::Shader(gl::ShaderType::eFrag);
frag.source("#version 150\nout vec4 outColor; void main() { outColor = vec4(1.0, 0.0, 0.0, 1.0); }");
frag.compile();

program.attach(vert);
program.attach(frag);
program.link();
``` 

Should the abstraction go further, like making every construct a RAII class? OOGL opted for not only making constructs RAII classes but also making constructors that make assumptions like:

```cpp
// Shader is already compiled after construction.
GL::Shader vert(GL::ShaderType::Vertex, "#version 150\nin vec2 position; void main() { gl_Position = vec4(position, 0.0, 1.0); }");
GL::Shader frag(GL::ShaderType::Fragment, "#version 150\nout vec4 outColor; void main() { outColor = vec4(1.0, 0.0, 0.0, 1.0); }");
// Program is compiled after construction.
GL::Program program(vert, frag);
```

## Questions

1. What would need to be done to make library like Vulkan-Hpp but for OpenGL?

2. How would it be able to get official Khronos support if that were the case?

**Comment by jherico** [comment] 2016-11-17 20:44
You might want to look at [OGLplus](http://oglplus.org/)

**Comment by ioquatix** [comment] 2017-01-30 09:10
> I love how Vulkan-Hpp offers OOP patterns and compile time type checking for Vulkan constructs, and I'm wondering if there's any plans to bring that same style of header only library to OpenGL as an officially maintained library.

This will never be possible in the general sense.

The problem is that Vulkan is designed fundamentally around objects and an object-dispatch system, OpenGL is built around a state-machine. The OpenGL state-machine is not well suited for an OO wrapper.

Additionally, Vulkan-Hpp is built from an XML API specification. AFAIK, no such spec exists for OpenGL.

**Comment by asuessenbach** [comment] 2017-02-10 14:47
I consider this answered by ioquatix. Closing.

**Closed by asuessenbach** 2017-02-10 14:47 UTC

**Comment by acterhd** [comment] 2017-02-18 02:06
I made own OpenGL wrapper, based on DSA. 
But I anyway want official OpenGL C++ library....
