### ISSUE TITLE
'caught exception: basic_string::_M_construct null not valid' if use vk.xml from https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/Vulkan-Hpp#25] opened 2016-08-28 16:34 UTC
when launch:

```VulkanHppGenerator foo/Vulkan-Docs/src/spec/vk.xml```

and the vk.xm file is latest version of https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml (https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/85184f305afe0f2e9e99cc9525e8ce25c32e74e0/src/spec/vk.xml)

gets

```
caught exception: basic_string::_M_construct null not valid
```

```
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/tmp/makepkg/vulkan-git/src/build-vulkan-hpp]|
└───╼  ./VulkanHppGenerator /tmp/makepkg/vulkan-git/src/Vulkan-Docs/src/spec/vk.xml 
Loading vk.xml from /tmp/makepkg/vulkan-git/src/Vulkan-Docs/src/spec/vk.xml
Writing vulkan.hpp to /tmp/makepkg/vulkan-git/src/Vulkan-Hpp/vulkan/vulkan.hpp
caught exception: basic_string::_M_construct null not valid
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/tmp/makepkg/vulkan-git/src/build-vulkan-hpp]|
└───╼  echo $?
255
```

**Comment by mtavenrath** [comment] 2016-08-29 08:00
The enums VkExternalMemoryHandleTypeFlagBitsNV and VkExternalMemoryFeatureFlagBitsNV are missing the type attribute. I've replaced the debug asserts which checks for the correct form of an enums tag by std::runtime_errors to give better errors in the future.

Closing as this is not a bug of the generator, but of the spec.

**Closed by mtavenrath** 2016-08-29 08:00 UTC

**Comment by mtavenrath** [comment] 2016-08-29 08:20
Until the issue is fixed in the spec add type="bitmask" to
<enums name="VkExternalMemoryHandleTypeFlagBitsNV">(line 3060) and
<enums name="VkExternalMemoryFeatureFlagBitsNV"> (line 3066)

**Comment by oddhack** [comment] 2016-08-29 10:01
I've filed an internal MR to tweak the canonical vk.xml. Once NVIDIA signs off on it, that will go into the weekly spec updates.

**Comment by sl1pkn07** [comment] 2016-08-29 18:34
thanks @mtavenrath !
