### ISSUE TITLE
Vulkan-Tools reporting 'operator==' is ambiguous when using the v1.1.125 headers

### ISSUE THREAD

**Issue by shannon-lunarg** [KhronosGroup/Vulkan-Hpp#410] opened 2019-10-18 17:29 UTC
When building `vkcube` in Vulkan-Tools with the v1.1.125 headers, 37 errors crop up related to 'operator ==' being ambiguous for various struct members in `vulkan.hpp`.

The first mention of the problem:
```
C:\j\w0\32-bit\Release\external\Vulkan-Headers\build\install\include\vulkan/vulkan.hpp(20938): error C2593: 'operator ==' is ambiguous [C:\j\w0\32-bit\Release\build32\cube\vkcubepp.vcxproj]
```
[The full AppVeyor log](
https://ci.appveyor.com/project/Khronoswebmaster/vulkan-tools/builds/28194061)

**Comment by KarenGhavam-lunarG** [comment] 2019-10-23 19:38
@mtavenrath Can we get somebody to treat this with some urgency? It is blocking a header update that is also blocking an SDK release.

**Comment by mtavenrath** [comment] 2019-10-24 07:50
@shannon-lunarg @KarenGhavam-lunarG Can you provide more information on how to reproduce this issue. I've taken the latest vulkan headers (1.1.125), copied them over to the latest vulkan sdk and built vkcube/vkcubehpp using visual studio 2019 for 32-bit and 64-bit targets without any problems.

**Comment by shannon-lunarg** [comment] 2019-10-24 16:06
@mtavenrath What jumps out to me is that AppVeyor in the Khronos Vulkan repos uses Visual Studio 2015.

Also, this is the known good file which outlines which version of each repo my `shannon-125-update-known-good` branch is using: [https://github.com/KhronosGroup/Vulkan-Tools/blob/shannon-125-update-known-good/scripts/known_good.json](https://github.com/KhronosGroup/Vulkan-Tools/blob/shannon-125-update-known-good/scripts/known_good.json).

**Comment by mtavenrath** [comment] 2019-10-25 06:18
I'm surprised that this didn't pop up ealier. This is some msvc 2015 bug and the workaround seems to be replacing stage == rhs.stage by vk::operator==(stage, rhs.stage). I'll see how I can incorporate this change into the code generator.

**Comment by mtavenrath** [comment] 2019-10-25 11:22
correction. the issue has been caused by one of the latest commits. I just submitted a change which make vkcubepp compile again.

**Comment by shannon-lunarg** [comment] 2019-10-25 19:28
Yes, these changes fix the errors I was seeing and I have created a PR in Vulkan-Headers to pick up this version of `vulkan.hpp` immediately. Thank you so much for your help!

**Comment by mtavenrath** [comment] 2019-10-28 14:42
@shannon-lunarg A small typo got introduced into the Vulkan-Hpp fix which broke operator==. Another update is necessary!

**Comment by shannon-lunarg** [comment] 2019-10-28 17:19
@mtavenrath Oh, yes, thanks for the heads up. I will pull that fix over into Vulkan-Headers.

**Comment by KarenGhavam-lunarG** [comment] 2019-10-28 17:26
@mtavenrath We need to support VS2015 across multiple repositories and hence why we found this issue. Is it correct to assume that a cpp program is never built with VS2015 as a default on this repository and hence why you didn't find the issue initially? Is it unreasonable to ask for that?

**Comment by mtavenrath** [comment] 2019-11-05 05:53
Issue is solved. Closing.

**Closed by mtavenrath** 2019-11-05 05:53 UTC
