### ISSUE TITLE
vk::UniqueSurfaceKHR creation is broken, and thus impossible

### ISSUE THREAD

**Issue by john01dav** [KhronosGroup/Vulkan-Hpp#478] opened 2020-01-10 16:36 UTC
I am currently re-doing the code that is needed to make a triangle appear using vulkan.hpp instead of vulkan.h, to learn how to use vulkan.hpp. Because I believe in using RAII to its fullest extent, I am extensively using vulkan.hpp's unique pointers. When I got to surface creation, however, I hit a major brick wall. It seems that the only official documentation that I can find (README.md) neglects to explain how to create a `vk::UniqueSurfaceKhr` instance, since one obviously can't use the `vk::createSurfaceUnique` pattern because it isn't cross-platform in this case (I write all of my code, including Cmake and such, to be entirely cross-platform, and leave platform-specific things like surface creation to libraries, in this case, SFML — although GLFW would produce the same result). After some quite time consuming Internet searching and guessing (I intend to PR a fix to the documentation once this issue is resolved.), I found that one is supposed to pass a `vk::Instance` instance to `vk:UniqueSurfaceKHR`'s constructor as the second argument, but, when I do this, I get a compiler error:

Minimum example:
```
#include <vulkan/vulkan.hpp>

int main(){
        //proper initialization is not needed becuase this program exists solely to produce the reported compiler error
        VkInstance instance; //also happens with vk::Instance
        VkSurfaceKHR surface; //also happens with vk::SurfaceKHR
        auto uniqueSurface = vk::UniqueSurfaceKHR(surface, instance);
        return 0;
}
```

Compilation command (gcc 9.2.0 on Linux with Vulkan SDK 1.1.130 according to Arch Linux's package version):
`g++ --std=c++17 vulkantest.cpp -o vulkantest`

Compiler error:
```
vulkantest.cpp: In function ‘int main()’:
vulkantest.cpp:7:61: error: no matching function for call to ‘vk::UniqueHandle<vk::SurfaceKHR, vk::DispatchLoaderStatic>::UniqueHandle(VkSurfaceKHR_T*&, VkInstance_T*&)’
    7 |  auto uniqueSurface = vk::UniqueSurfaceKHR(surface, instance);
      |                                                             ^
In file included from vulkantest.cpp:1:
/usr/include/vulkan/vulkan.hpp:609:5: note: candidate: ‘vk::UniqueHandle<Type, Dispatch>::UniqueHandle(vk::UniqueHandle<Type, Dispatch>&&) [with Type = vk::SurfaceKHR; Dispatch = vk::DispatchLoaderStatic]’
  609 |     UniqueHandle( UniqueHandle && other ) VULKAN_HPP_NOEXCEPT
      |     ^~~~~~~~~~~~
/usr/include/vulkan/vulkan.hpp:609:5: note:   candidate expects 1 argument, 2 provided
/usr/include/vulkan/vulkan.hpp:602:14: note: candidate: ‘vk::UniqueHandle<Type, Dispatch>::UniqueHandle(const Type&, const Deleter&) [with Type = vk::SurfaceKHR; Dispatch = vk::DispatchLoaderStatic; vk::UniqueHandle<Type, Dispatch>::Deleter = vk::ObjectDestroy<vk::Instance, vk::DispatchLoaderStatic>]’
  602 |     explicit UniqueHandle( Type const& value, Deleter const& deleter = Deleter() ) VULKAN_HPP_NOEXCEPT
      |              ^~~~~~~~~~~~
/usr/include/vulkan/vulkan.hpp:602:62: note:   no known conversion for argument 2 from ‘VkInstance’ {aka ‘VkInstance_T*’} to ‘const Deleter&’ {aka ‘const vk::ObjectDestroy<vk::Instance, vk::DispatchLoaderStatic>&’}
  602 |     explicit UniqueHandle( Type const& value, Deleter const& deleter = Deleter() ) VULKAN_HPP_NOEXCEPT
      |                                               ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan.hpp:597:5: note: candidate: ‘vk::UniqueHandle<Type, Dispatch>::UniqueHandle() [with Type = vk::SurfaceKHR; Dispatch = vk::DispatchLoaderStatic]’
  597 |     UniqueHandle()
      |     ^~~~~~~~~~~~
/usr/include/vulkan/vulkan.hpp:597:5: note:   candidate expects 0 arguments, 2 provided

```

I also tried compiling against the latest vulkan.hpp file from this Github repository (linked in README), which produces the same error; with clang 9.0.1 (same command), which also produces the same error; in an actual project where all of Vulkan is properly linked via Cmake (in such a way that a triangle appears with the C API); and with all C++ standards since C++11. 

Because this error occurs in multiple C++ compilers and standard versions and due to the method that I am using for RAII with `VkSurfaceKHR` being all that I can find ([link](https://www.reddit.com/r/vulkan/comments/b2rtk5/vulkanhpp_making_a_unique_instance_from_non_unique/eiup1ex?utm_source=share&utm_medium=web2x), [link](https://github.com/KhronosGroup/Vulkan-Hpp/issues/242#issuecomment-416710305)), this looks like a regression in vulkan.hpp that should be fixed quickly since it blocks an essential feature for even basic graphics use of Vulkan with modern C++ (which implies liberal use of RAII).

**Comment by pierremoreau** [comment] 2020-01-11 13:54
I believe this is a duplicate of #467, which has already been fixed in master.

**Closed** 2020-01-11 16:17 UTC
