### ISSUE TITLE
[feature request] do not overwrite pNext in overloaded operator=

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Hpp#1586] opened 2023-06-06 15:13 UTC
Currently, when using `vk::StructureChain` I should do:
```cpp
vk::StructureChain<vk::A, vk::B, vk::C> createInfoChain;

auto& a = createInfoChain.get<vk::A>();
a.flags = {};
a.x = ...;
a.y = ...;
...

auto& b = createInfoChain.get<vk::B>();
b.flags = {};
b.z = ...;
b.t = ...;
...

auto& c = createInfoChain.get<vk::C>();
```
but actually I want to do the next:
```cpp
vk::StructureChain<vk::A, vk::B, vk::C> createInfoChain;

createInfoChain.get<vk::A>() = {
    .flags = {},
    .x = ...,
    .y = ...,
    ...,
};

createInfoChain.get<vk::B>() = {
    .flags = {},
    .x = ...,
    .y = ...,
    ...,
};

createInfoChain.get<vk::A>() = {
    ...,
};
```
I want to use [field's designators](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers). It is currently normal to want to (after C++20). But there is a problem: in second snippet all the `pNext`s are unlinked (effectively `nullptr` is assigned to each of them). To alleviate this it is required to add/change overloaded `operator =` implementation, which avoids `pNext`'s assignment.

**Comment by theHamsta** [comment] 2023-06-11 12:59
Hi! I think unconditionally ignoring the `.pNext` field in `operator=` might be a bit unexpected. Maybe there could be a special sentinel value for pNext that leaves its value unchanged in `operator=`?

In general, I would expect the more natural to work with designated initializers to be

```
vk::StructureChain<vk::A, vk::B, vk::C> createInfoChain {{
    .flags = {},
    .x = ...,
    .y = ...,
    ...,
}, {
    .flags = {},
    .x = ...,
    .y = ...,
    ...,
}, {
    ...,
}};
```
which should work already

**Comment by theHamsta** [comment] 2023-06-11 14:04
Maybe a builder pattern would also be suited for that situation.
```
Hi! I think unconditionally ignoring the `.pNext` field in `operator=` might be a bit unexpected. Maybe there could be a special sentinel value for pNext that leaves its value unchanged in `operator=`?

In general, I would expect the more natural to work with designated initializers to be

```cpp
auto createInfoChain = vk::ABuilder()
                                            .flags(...)
                                            .x(...)
                                            .y(...)
                                            .next<B>() // now a vk::StructureChainBuilder<vk::A, vk::B>
                                            .flags(...)
                                            .next<C>() // now a vk::StructureChainBuilder<vk::A, vk::B, vk::C>
                                            .flags(...)
                                            .build(); //  now a vk::StructureChain<vk::A, vk::B, vk::C>

```

**Comment by asuessenbach** [comment] 2023-06-14 12:08
This issue is a duplicate of #1575.
That is, there seems to be some demand for such a functionality.
But, as @theHamsta already stated, skipping `pNext` in `operator=()` would probably be unexpected.
As this is all about StructureChain usage, maybe we can introduce some templated function `StructureChain::assign<>()` (with similar template arguments as `StructureChain::get<>()`), that would actually preserve the `pNext` value in the chain?

**Comment by tomilov** [comment] 2023-06-14 14:59
@theHamsta initialization of all the members in a constructor has limitations if one want to initialize chain elements one by one because of some reason.

@asuessenbach the only sane solution, I think.
Insane one is to return some specialization of special type:
```
template<...>
struct StructureChain
{
    ...
    template<typename Struct>
    Assigner<Struct> get(); // non-const only
    ...
};

template<typename Struct>
struct Assigner
{
    Struct& lhs;

    constexpr Struct& operator=(const Struct& rhs) const noexcept
    {
        auto pNext = lhs.pNext;
        lhs = rhs;
        lhs.pNext = pNext;
        return lhs;
    }
};
```
but it has big disadvantage: it not fully mimic `Struct`, because it is impossible to overload `operator .` to be able to access `Struct`'s members like:
```
vk::StructureChain<vk::A, vk::B> aChain;
auto&& a = aChain.get<vk::A>();
a = vk::A{
    .flags = {},
    .x = 123,
};
// the one want to change one field:
a.x = 321; // but it is impossible. Possible only in form a.rhs.x = 321; but symbol rhs is something too artificial for API's users
```

**Closed** 2023-06-21 11:36 UTC
